openapi: '3.0.2'
info:
  title: Customer API
  version: '1.0'
servers:
  - url: https://localhost:8080/customer

tags:
  - name: Customer API

paths:
  /customer:
    post:
      description: create customer information
      operationId: createCustomer
      tags:
        - "Customer API"
      requestBody: 
         content:
           application/json:
              schema:
                $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: OK
          content:
             application/json:
                schema:
                 $ref: '#/components/schemas/Customer'
        '500':
          description: Internal Server Error
  /customer/{id}:
    get:
      description: Get/Fetch customer details
      operationId: getCustomer
      parameters:
        - name: id
          in: path
          description: find Customer
          required: true
          schema:
            type: string
      tags:
        - "Customer API"
      responses:
        '200':
          description: OK
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'       
        '400':
          description: Invalid Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error

components:
  schemas:
    Customer:
      description: This is a customer schema
      type: object
      required:
        - "customerId"
      properties:
        customerId: 
          type: string
          description: this is customer ID
          example: 12345
          minLength: 5
          maxLength: 8
        customerName:
          type: string
          description: this is customer name
          example: John Smith
        customerAddress:
          type: string
          description: this is customer address
          example: 11 main street